### ISSUE TITLE
error on importing plugin

### ISSUE THREAD

**Issue by miztizm** [alexandrevicenzi/hexchat-emoji#1]
hexchat 2.14

`Traceback (most recent call last):
   File "/home/xxx/.config/hexchat/addons/emojis/emojis.py", line 3, in <module>
     from . import db
 ImportError: cannot import name 'db'
 Error loading module /home/xxx.config/hexchat/addons/emojis/emojis.py`

**Comment by unix1984** [comment]
![elhagyatva](https://user-images.githubusercontent.com/78550977/114190928-273ff800-994c-11eb-9dd8-00eac0a78231.gif)

**Comment by alexandrevicenzi** [comment]
I'm not able to reproduce this error.

You need to reinstall emojis or upgrade your Python to 3.x.

**Comment by unix1984** [comment]
![python3x_installed](https://user-images.githubusercontent.com/78550977/114516515-c52e0e00-9c3d-11eb-9aa8-82fd587e2f55.png)

**Comment by alexandrevicenzi** [comment]
If you don't know how to report an issue I can't do anything about it.

Closing this as there's no data to debug and or back that this is a real issue.
