### ISSUE TITLE
Weird error with certain messages

### ISSUE THREAD

**Issue by LoneWolfHT** [alexandrevicenzi/hexchat-emoji#5]
![image](https://user-images.githubusercontent.com/28972859/119024219-b4b53580-b957-11eb-8319-99862b4edc0a.png)
(error happens before the message that triggered it)

**Comment by alexandrevicenzi** [comment]
This seems odd, did you change some config in the script?

What version of HexChat and what distro are you using?
Is it snap, flatpak or the package from your distro?

**Comment by LoneWolfHT** [comment]
I'm using `Manjaro 21.0.4 Ornara` with `Hexchat 2.14.3`

No configs changed, directly copied the file from Github master
Downloaded hexchat from `community` with pamac

This is what the python plugin (not the `emoji` one, to be clear) looks like in Hexchat (my other plugins are hidden) 
![image](https://user-images.githubusercontent.com/28972859/119201312-7d23b780-ba43-11eb-83bd-dc9736a94586.png)

**Comment by alexandrevicenzi** [comment]
Do you have other plugins or addons enabled? Can you share the full list?

You could change `msg_cb` and post the results for me

```python
def msg_cb(words, word_eol, userdata):
    print("***")
    print(words, word_eol, userdata)
    print("***")
```

It will print the result in the chat, only for you, not for other, such as

```
        ***
        ['sd'] ['sd'] None
        ***
<nick>: sd
```

This change will help understand what is coming as parameters.

For some reason, the plugin is not getting the message in `word_eol[0]`, acording to HexChat documentation, this is always populated, it's either a bug in HexChat or another plugin is eating the input and crashing whoever tries to read the contents from HexChat.

**Comment by LoneWolfHT** [comment]
If I disable everything but python and your plugin it still fails.

I've narrowed down on what causes the error: You need a space before at least one letter for it to work:
![image](https://user-images.githubusercontent.com/28972859/119245505-ad945000-bb2e-11eb-9ba2-94c4511e73e0.png)

Oh, and `/say :)` converts the face to an emoji but just a plain `:)` message doesn't work, you still get the error with both though

*starts doing some testing*

It looks like this is a Hexchat/Python bug because this script in lua dumps the message fine:
```lua
local name = "test.lua"
local desc = "Test test test"
local version = "0.1"

local serpent = require("serpent")

hexchat.register(name, version, desc)

local function cmd_alias(word, eol)
	print(serpent.dump(word))
	return hexchat.EAT_NONE
end

hexchat.hook_command("", cmd_alias)

```
![image](https://user-images.githubusercontent.com/28972859/119246236-c6076900-bb34-11eb-8df7-94165c8b0dbf.png)

**Comment by alexandrevicenzi** [comment]
I updated the emoji plugin, but I doubt it will make any difference, but it won't crash at least.

I have HexChat version 2.12.4 (openSUSE) and 2.14.3 (Ubuntu), it could be a problem in the Manjaro/Arch packages. Once I have time I'll try it in Manjaro.

The "Enter Hit" or just plain `:)` is basically calling `/say` in the end, but for HexChat plugins, for some reason, it's not the same command, but the command `""` (empty) captures `/say` and Enter in the input box. It seems odd to me that `/say` works and plain `:)` does not.

I could write this plugin in Lua one day, or perhaps someone could contribute a Lua version.

**Comment by LoneWolfHT** [comment]
Alright, thanks!
